ARG BUILD_FROM=python:3.13-slim
FROM ${BUILD_FROM}

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app/ ./app/
COPY parser/ ./parser/
COPY run.sh /run.sh
RUN chmod +x /run.sh

CMD ["/run.sh"]
